application: cloudbday
version: 2014q1032
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: lxml
  version: "latest"
- name: endpoints
  version: "latest"

inbound_services:
- warmup

error_handlers:
  - file: birthday/static/html/default_error.html

  - error_code: over_quota
    file: birthday/static/html/over_quota.html

  - error_code: dos_api_denial
    file: birthday/static/html/dos.html

  - error_code: timeout
    file: birthday/static/html/timeout.html

handlers:
- url: /favicon.ico
  static_files: birthday/static/img/favicon.ico
  upload: birthday/static/img/favicon.ico

- url: /robots.txt
  static_files: birthday/static/robots.txt
  upload: birthday/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /_ah/spi/.*
  script: run.api

- url: /_ah/queue/deferred
  script: run.deferred_app
  login: admin

- url: /static
  static_dir: birthday/static

- url: .*
  script: run.birthday.app